<project xmlns="http://maven.apache.org/POM/4.0.0"
 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
 	<modelVersion>4.0.0</modelVersion>
 	
 	<parent>
 		<groupId>com.kt.kol</groupId>
 		<artifactId>kol-rest-api</artifactId>
 		<version>0.0.1</version>
 	</parent>
 	
 	<artifactId>rest-api</artifactId>

 	<dependencies>
 		<!-- Internal modules -->
 		<dependency>
 			<groupId>com.kt.kol</groupId>
 			<artifactId>common</artifactId>
 		</dependency>
 		
 		<!-- Spring Boot starters -->
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-webflux</artifactId>
 		</dependency>
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-data-r2dbc</artifactId>
 		</dependency>
 		
 		<!-- OpenAPI documentation -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
		</dependency>
		
		<!-- Testing -->
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-test</artifactId>
 			<scope>test</scope>
 		</dependency>
 		<dependency>
 			<groupId>io.projectreactor</groupId>
 			<artifactId>reactor-test</artifactId>
 			<scope>test</scope>
 		</dependency>
 		
 		<!-- Utilities -->
 		<dependency>
 			<groupId>org.projectlombok</groupId>
 			<artifactId>lombok</artifactId>
 			<optional>true</optional>
 		</dependency>
 		
 		<!-- Database -->
 		<dependency>
 			<groupId>org.postgresql</groupId>
 			<artifactId>postgresql</artifactId>
 		</dependency>
 		<dependency>
 			<groupId>org.postgresql</groupId>
 			<artifactId>r2dbc-postgresql</artifactId>
 		</dependency>
 		
 		<!-- BMON API -->
 		<dependency>
 		    <groupId>com.kt.icis</groupId>
 		    <artifactId>onm-bmon-api</artifactId>
 		    <version>2.0.0</version>
 		    <scope>system</scope>
 		    <systemPath>${lib.external.dir}/com/kt/icis/onm-bmon-api/2.0.0/onm-bmon-api-2.0.0.jar</systemPath>
 		</dependency>
 		
 		<!-- JSON Flattener -->
 		<dependency>
 		    <groupId>com.github.wnameless.json</groupId>
 		    <artifactId>json-flattener</artifactId>
 		    <version>0.17.3</version>
 		</dependency>
 	</dependencies>
 	
</project>