# spring default
spring:
  profiles:
    active: local
  application:
    name: kol-rest-api

server:
  port: 8080
  bmon: true
  servlet.context-path: /kol-rest-api

# spring boot - actuator expose
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: health, loggers, prometheus
  endpoint:
    health:
      show-details: always

---
# Profile - local
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
  r2dbc:
    url: ${R2DBC_URL_DEV}
    username: ${R2DBC_USER_NAME}
    password: ${DB_PWD}
server:
  port: 8003

logging:
  config: classpath:logback-spring-dev.xml
  file:
    name: kol-rest-api
    path: /var/log
e2e:
  properties:
    path: /KOS-OL/workspace_final/kol-rest-gw/core/config/bmon/dev
gw.itg.url: http://127.0.0.1:8001

---
# Profile - dev
spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: ${R2DBC_URL_DEV}
    username: ${R2DBC_USER_NAME}
    password: ${DB_PWD}
logging:
  config: classpath:logback-spring-dev.xml
  file:
    name: kol-rest-api
    path: /var/log
e2e:
  properties:
    path: /config/bmon/dev
gw.itg.url: http://kol-itg-gw

management:
  health:
    r2dbc:
      enabled: false
    db:
      enabled: false

---
# Profile - sit
spring:
  config:
    activate:
      on-profile: sit
  r2dbc:
    url: ${R2DBC_URL_SIT}
    username: ${R2DBC_USER_NAME}
    password: ${DB_PWD}
logging:
  config: classpath:logback-spring-sit.xml
  file:
    name: kol-rest-api
    path: /var/log
e2e:
  properties:
    path: /config/bmon/sit
gw.itg.url: http://kol-itg-gw

management:
  health:
    r2dbc:
      enabled: false
    db:
      enabled: false

---
# Profile - prd
spring:
  config:
    activate:
      on-profile: prd
  r2dbc:
    url: ${R2DBC_URL_PRD}
    username: ${R2DBC_USER_NAME}
    password: ${DB_PWD}
logging:
  config: classpath:logback-spring-prd.xml
  file:
    name: kol-rest-api
    path: /var/log
e2e:
  properties:
    path: /config/bmon/prd
gw.itg.url: http://kol-itg-gw
